<?php

namespace App\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleEntityRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ArticleEntityRepository extends EntityRepository
{
}
